name = "Dartis-Craft SpiritualCraft v2.0"
author = "DartisXUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f997b946ef706319d95cec15e2b60f108e0691e90ecebf0963488581162099b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
