name = "Dartis-Craft SpiritualCraft v2.0"
author = "DartisXUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4009c4748485f62dba7331754447be5c12e3101f187d38aaca2215d74f2be63"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
