name = "Dartis-Craft SpiritualCraft v2.0"
author = "DartisXUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba6fb8d438ada0ddd68d865008d27953bfa6a9a5b572810872a17663ec9c3063"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
