name = "Dartis-Craft SpiritualCraft v2.0"
author = "DartisXUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d520599a12da9061358d5db823fd620b1edec3e64b430ec7d659dfa04822735e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
