name = "Dartis-Craft SpiritualCraft v2.0"
author = "DartisXUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "060a3191ec1e8b10bdbc9240d2d0cc57c3f6cb77073e0a49da7762e0612d758e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
