name = "Dartis-Craft SpiritualCraft v2.0"
author = "DartisXUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84a3baf88dddd1a43c10ff7880577984b824b3cca5122711c78c80897a57813d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
